// Code generated by go generate; DO NOT EDIT.

package repository

// Reset сбрасывает все поля структуры SafeMap к их нулевым значениятам.
func (c *SafeMap) Reset() {
	if c == nil {
		return
	}
	c.mu.Unlock()
	clear(c.m)
	c.counter = 0
}
