// Code generated by go generate; DO NOT EDIT.

package repository

import "sync"

// Reset сбрасывает все поля структуры SafeMap к их нулевым значениятам.
func (c *SafeMap) Reset() {
	c.mu = sync.RWMutex{}
	c.m = nil
	c.counter = 0
}
