package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/mrechkunov/golangShortener.git/internal/logger"
)

const newFile = `
// Code generated by go generate; DO NOT EDIT.

package {{.PackageName}}
`
const resetTemplate = `
// Reset сбрасывает все поля структуры {{.StructName}} к их нулевым значениятам.
func (c *{{.StructName}}) Reset() {
{{range .StructFields}}	c.{{.Name}} = {{.ZeroValue}}
{{end}}}`

// Структура для передачи данных в шаблон
type FieldData struct {
	Name      string
	ZeroValue string
}

type StructsToReset struct {
	PackageName  string
	StructName   string
	StructFields []FieldData
}

func ExprToString(expr ast.Expr) (string, error) {
	var buf bytes.Buffer
	// fset is required to track positions; for a single expr, a new one is fine.
	fset := token.NewFileSet()
	err := format.Node(&buf, fset, expr)
	if err != nil {
		return "", err
	}
	return buf.String(), nil
}

func searchComment(projectDir string, comment string) {
	var currentDir string
	// Рекурсивный обход всех файлов в директории для сбора слайса с позициями комментария
	err := filepath.Walk(projectDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			currentDir = path
		}
		var sList []StructsToReset

		// Обрабатываем только Go-файлы (игнорируя директории и тесты)
		if !info.IsDir() && strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
			// Парсим файл в AST
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
			if err != nil {
				return fmt.Errorf("ошибка парсинга %s: %v", path, err)
			}
			var targetComment *ast.Comment

			// ищем комментации в файле
			for _, group := range f.Comments {
				for _, c := range group.List {
					// если комментарий совпадает с шаблоном выводим что комментарий найден и добавляем его в слайс комментов
					if c.Text == comment {
						targetComment = c
						targetPos := targetComment.End()
						var nextNode ast.Node

						// Обходим узлы AST
						ast.Inspect(f, func(n ast.Node) bool {
							// Если мы уже нашли нужную ноду, выходим из обхода вглубь
							if nextNode != nil {
								return false
							}
							// Нас интересуют только объявления типов
							typeSpec, ok := n.(*ast.TypeSpec)
							if !ok {
								return true
							}
							// Проверяем, является ли тип структурой
							structType, isStruct := typeSpec.Type.(*ast.StructType)
							if isStruct && n.Pos() > targetPos {
								// fmt.Printf("Найдена структура: %s\n", typeSpec.Name.Name)
								// fmt.Println("Имя пакета:", f.Name.Name)
								var s StructsToReset
								s.PackageName = f.Name.Name
								s.StructName = typeSpec.Name.Name
								var fd FieldData
								// Перебираем поля структуры
								for _, field := range structType.Fields.List {
									for _, name := range field.Names {
										//fmt.Printf("  Поле: %s, Тип: %v\n", name.Name, field.Type)
										ft, err := ExprToString(field.Type)
										if err != nil {
											logger.Log.Infoln(err)
										}
										var zv string
										switch ft {
										case "int", "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64":
											zv = "0"
										case "float32", "float64":
											zv = "0"
										case "string":
											zv = "\"\""
										case "bool":
											zv = "false"
										case "time.Time":
											zv = "time.Time{}"
										case "sync.RWMutex":
											zv = "sync.RWMutex{}"
										default:
											zv = "nil"
										}
										fd.Name = name.Name
										fd.ZeroValue = zv
										s.StructFields = append(s.StructFields, fd)
									}
								}
								nextNode = n
								sList = append(sList, s)
							}
							return true
						})

					}
				}
			}
			generateResetFunc(sList, currentDir)
		}

		return nil
	})
	if err != nil {
		logger.Log.Warnln("Ошибка обхода проекта: %v\n", err)
	}
}

// TODO

// 3. написать генератор кода для всех типов структур
func main() {
	if len(os.Args) < 2 {
		logger.Log.Infoln("Использование: go run main.go <путь_к_директории_проекта>")
		return
	}
	projectDir := os.Args[1]
	searchComment(projectDir, "//generate:reset")

}

func testprint(str []StructsToReset, path string) {
	fmt.Println(path)
	for _, s := range str {
		fmt.Println("Имя пакета:", s.PackageName)
		fmt.Println("Имя Структуры:", s.StructName)
		for _, f := range s.StructFields {
			fmt.Println("поле:", f.Name, " ZeroValue", f.ZeroValue)
		}

	}
}

func generateResetFunc(strToGenerate []StructsToReset, path string) {

	if len(strToGenerate) > 0 {
		// Парсинг шапки шаблона
		tmpl, err := template.New("head").Parse(newFile)
		if err != nil {
			panic(err)
		}
		// Создание файла, куда будет записан сгенерированный код
		filename := path + "/reset.gen.go"
		fmt.Println(filename)
		file, err := os.OpenFile(filename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0666)
		if err != nil {
			logger.Log.Warnln(err)
		}
		defer file.Close()

		// Применение шаблона шапки и запись в файл
		err = tmpl.Execute(file, strToGenerate[0])
		if err != nil {
			panic(err)
		}

		// Парсинг шаблона
		tmplfuncs, err := template.New("reset").Parse(resetTemplate)
		if err != nil {
			panic(err)
		}
		for _, structToGenetate := range strToGenerate {
			// Применение шаблона  и запись в файл
			err = tmplfuncs.Execute(file, structToGenetate)
			if err != nil {
				panic(err)
			}
			// форматируем созданный файл
			// Читаем исходный код файла
			src, err := os.ReadFile(filename)
			if err != nil {
				log.Fatal(err)
			}

			// Применяем стандартное gofmt форматирование
			formatted, err := format.Source(src)
			if err != nil {
				log.Fatal(err)
			}

			// Перезаписываем файл отформатированным кодом
			err = os.WriteFile(filename, formatted, 0644)
			if err != nil {
				log.Fatal(err)
			}
			// Команда goimports с флагом -w (записать изменения обратно в файл)
			cmd := exec.Command("goimports", "-w", filename)

			// Запуск команды
			err = cmd.Run()
			if err != nil {
				log.Fatalf("Ошибка при выполнении goimports: %v", err)
			}

		}
	}
}
